package com.xxcactussell.domain

import com.xxcactussell.repositories.chats.model.ChatStatus

data class Chat(
    val id: Long,
    val type: ChatType,
    val title: String,
    val photo: ChatPhotoInfo? = null,
    val accentColorId: Int,
    val backgroundCustomEmojiId: Long,
    val profileAccentColorId: Int,
    val profileBackgroundCustomEmojiId: Long,
    val permissions: ChatPermissions,
    val lastMessage: Message? = null,
    val positions: List<ChatPosition>,
    val chatLists: List<ChatList>,
    val messageSenderId: MessageSender? = null,
    val blockList: BlockList? = null,
    val hasProtectedContent: Boolean,
    val isTranslatable: Boolean,
    val isMarkedAsUnread: Boolean,
    val viewAsTopics: Boolean,
    val hasScheduledMessages: Boolean,
    val canBeDeletedOnlyForSelf: Boolean,
    val canBeDeletedForAllUsers: Boolean,
    val canBeReported: Boolean,
    val defaultDisableNotification: Boolean,
    val unreadCount: Int,
    val lastReadInboxMessageId: Long,
    val lastReadOutboxMessageId: Long,
    val unreadMentionCount: Int,
    val unreadReactionCount: Int,
    val notificationSettings: ChatNotificationSettings,
    val availableReactions: ChatAvailableReactions,
    val messageAutoDeleteTime: Int,
    val emojiStatus: EmojiStatus? = null,
    val background: ChatBackground? = null,
    val theme: ChatTheme? = null,
    val actionBar: ChatActionBar? = null,
    val businessBotManageBar: BusinessBotManageBar? = null,
    val videoChat: VideoChat,
    val pendingJoinRequests: ChatJoinRequestsInfo? = null,
    val replyMarkupMessageId: Long,
    val draftMessage: DraftMessage? = null,
    val clientData: String,
    val status: UserStatus = UserStatusEmpty,
    val myMemberStatus: ChatMemberStatus? = null,
    val memberCount: Int? = null
) : Object
