package com.xxcactussell.domain

import com.xxcactussell.customdomain.ForwardFullInfo

data class Message(
    val id: Long,
    val senderId: MessageSender,
    val chatId: Long,
    val sendingState: MessageSendingState? = null,
    val schedulingState: MessageSchedulingState? = null,
    val isOutgoing: Boolean,
    val isPinned: Boolean,
    val isFromOffline: Boolean,
    val canBeSaved: Boolean,
    val hasTimestampedMedia: Boolean,
    val isChannelPost: Boolean,
    val isPaidStarSuggestedPost: Boolean,
    val isPaidTonSuggestedPost: Boolean,
    val containsUnreadMention: Boolean,
    val date: Int,
    val editDate: Int,
    val forwardInfo: MessageForwardInfo? = null,
    val importInfo: MessageImportInfo? = null,
    val interactionInfo: MessageInteractionInfo? = null,
    val unreadReactions: List<UnreadReaction>,
    val factCheck: FactCheck? = null,
    val suggestedPostInfo: SuggestedPostInfo? = null,
    val replyTo: MessageReplyTo? = null,
    val messageThreadId: Long,
    val topicId: MessageTopic? = null,
    val selfDestructType: MessageSelfDestructType? = null,
    val selfDestructIn: Double,
    val autoDeleteIn: Double,
    val viaBotUserId: Long,
    val senderBusinessBotUserId: Long,
    val senderBoostCount: Int,
    val paidMessageStarCount: Long,
    val authorSignature: String,
    val mediaAlbumId: Long,
    val effectId: Long,
    val restrictionInfo: RestrictionInfo? = null,
    val content: MessageContent,
    val replyMarkup: ReplyMarkup? = null,
    val forwardFullInfo: ForwardFullInfo? = null
) : Object
