package com.xxcactussell.domain

data class SupergroupFullInfo(
    val photo: ChatPhoto? = null,
    val description: String,
    val memberCount: Int,
    val administratorCount: Int,
    val restrictedCount: Int,
    val bannedCount: Int,
    val linkedChatId: Long,
    val directMessagesChatId: Long,
    val slowModeDelay: Int,
    val slowModeDelayExpiresIn: Double,
    val canEnablePaidMessages: Boolean,
    val canEnablePaidReaction: Boolean,
    val canGetMembers: Boolean,
    val hasHiddenMembers: Boolean,
    val canHideMembers: Boolean,
    val canSetStickerSet: Boolean,
    val canSetLocation: Boolean,
    val canGetStatistics: Boolean,
    val canGetRevenueStatistics: Boolean,
    val canGetStarRevenueStatistics: Boolean,
    val canSendGift: Boolean,
    val canToggleAggressiveAntiSpam: Boolean,
    val isAllHistoryAvailable: Boolean,
    val canHaveSponsoredMessages: Boolean,
    val hasAggressiveAntiSpamEnabled: Boolean,
    val hasPaidMediaAllowed: Boolean,
    val hasPinnedStories: Boolean,
    val giftCount: Int,
    val myBoostCount: Int,
    val unrestrictBoostCount: Int,
    val outgoingPaidMessageStarCount: Long,
    val stickerSetId: Long,
    val customEmojiStickerSetId: Long,
    val location: ChatLocation? = null,
    val inviteLink: ChatInviteLink? = null,
    val botCommands: List<BotCommands>,
    val botVerification: BotVerification? = null,
    val mainProfileTab: ProfileTab? = null,
    val upgradedFromBasicGroupId: Long,
    val upgradedFromMaxMessageId: Long
) : Object
